commercetools.Sdk/Tests/commercetools.Api.Tests/ClientsFactoryTests.cs, commercetools.Sdk/commercetools.Base.Client/ClientConfiguration.cs, commercetools.Sdk/commercetools.Base.Client/ClientFactory.cs, commercetools.Sdk/commercetools.Base.Client/TokenProviderFactory.cs
Validate Client Configuration Model before Creating Client or before creating TokenProvider
=> Validate Client Configuration Model

commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/ImportApiDeserializationTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/ImportApiSerializationFixture.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/Resources/ImportApi/OperationStates.json, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/commercetools.Api.Serialization.Tests.csproj, commercetools.Sdk/commercetools.Base.Serialization/Extensions.cs, commercetools.Sdk/commercetools.Sdk.ImportApi/Serialization/JsonConverters/OperationStatesConverter.cs, commercetools.Sdk/commercetools.Sdk.ImportApi/Serialization/SerializerService.cs, commercetools.Sdk/commercetools.Sdk.ImportApi/commercetools.Sdk.ImportApi.csproj
Created Special converter to handle the pascal case in OperationStates Model
=> Fix Pascal deserialization issue in OperationStates in Import Api

Makefile, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/MessagesTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/MoneySerializationTests.cs, commercetools.Sdk/commercetools.Base.Abstractions/CustomAttributes/DefaultTypeDiscriminatorAttribute.cs, commercetools.Sdk/commercetools.Base.Client/DefaultClientNames.cs, commercetools.Sdk/commercetools.Base.Serialization/JsonConverters/TypeDiscriminatorConverter.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Common/ITypedMoney.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Common/TypedMoney.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Messages/IMessagePayload.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Messages/MessagePayload.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/Client/HistoryApiFactory.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/Client/HistoryApiRoot.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/Extensions/Extensions.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/Generated/Client/RequestBuilders/ByProjectKeyRequestBuilder.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/Serialization/SerializerService.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/commercetools.Sdk.HistoryApi.csproj, commercetools.Sdk/commercetools.Sdk.sln
- Adding HistoryApi SDK
- Introduce DefaultTypeDiscriminator Attribute
=> Adding HistoryApi SDK

COMPARISON.md, README.md
Create comparison document to show differences between SDK V1 and SDK V2
=> Comparison doc

commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/MessagesTests.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Subscriptions/IMessageDelivery.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Subscriptions/MessageDelivery.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/JsonConverters/MessageDeliveryConverter.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/SerializerService.cs
=> unwrap MessageDelivery Payloads as IMessage

README.md, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/ServiceProviderFixture.cs
Adding a new section for SetupClient extension method in ReadMe file
=> Adding a new section for SetupClient extension method

commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Controllers/HomeController.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Extensions/ProductExtensions.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Models/HomeViewModel.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Services/CartServices.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Services/ProductServices.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Services/Settings.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Startup.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Views/Home/Index.cshtml, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/appsettings.json
- Read Default Currency for cart from appsettings.json
- Added Extensions method "GetDisplayName" to display the default localized name of product & LineItem
- Get only published products by using ProductProjection endpoint instead of products endpoint
=> Checkout Example enhancements

commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/StandalonePricing/StandalonePricingTest.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/AttributesTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/SerializationTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/DateTimeTests.cs, commercetools.Sdk/commercetools.Base.Abstractions/Models/Date.cs, commercetools.Sdk/commercetools.Base.Serialization/BaseSerializerService.cs, commercetools.Sdk/commercetools.Base.Serialization/JsonConverters/CustomDateConverter.cs, commercetools.Sdk/commercetools.Base.Serialization/JsonConverters/CustomDateTimeConverter.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/ProjectApiRoot.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/ApiClients/ApiClient.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/ApiClients/IApiClient.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Customers/Customer.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Customers/CustomerDraft.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Customers/CustomerSetDateOfBirthAction.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Customers/ICustomer.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Customers/ICustomerDraft.cs, commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Customers/ICustomerSetDateOfBirthAction.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/SerializerService.cs
- add new Date struct to fix serialization of Date and DateTime values
=> fix serialization of dates and date times

commercetools.Sdk/commercetools.Sdk.Api/Client/ProjectApiRoot.cs
Add project scoped access to ProductSelections via Project Api Root
=> Add project scoped access to product selections

commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/README.md, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/appsettings.json
Hi,
I'm not sure if these files are normally autogenerated, but I added some documentation for setting up the ME Endpoint App and added some placeholders to the appsettings.json file.
=> Add documentation for ME Endpoint App

.github/workflows/ci.yml, commercetools.Sdk/commercetools.Sdk.Api/commercetools.Sdk.Api.csproj, license-check.sh, licenses/allowed.json, licenses/filter-projects.json, licenses/index.json, licenses/license-map.json
=> license check with allowed licenses

commercetools.Sdk/commercetools.Sdk.Api/Client/ProjectApiRoot.cs
Add project scoped access to Quotes, QuoteRequests and StagedQuotes via Project Api Root
=> Add project scoped access to quotes, quoteRequests and stagedQuotes

commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Extensions/ClientInjectionSetup.cs, commercetools.Sdk/Examples/commercetools.Api.ConsoleApp/Program.cs, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/Me/MeIntegrationTests.cs, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/ServiceProviderFixture.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/AttributesTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/ImportApiSerializationFixture.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/SerializationFixture.cs, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/ClientsFactoryTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/DateTimeTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/EnumTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/ProjectTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/RequestBuilderTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.ImportApi.Tests/EnumTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.ImportApi.Tests/ProductVariantPatchUnitTests.cs, commercetools.Sdk/commercetools.Sdk.Api/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/IApiSerializerService.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/SerializerService.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/Serialization/IHistorySerializerService.cs, commercetools.Sdk/commercetools.Sdk.HistoryApi/Serialization/SerializerService.cs, commercetools.Sdk/commercetools.Sdk.ImportApi/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Sdk.ImportApi/Serialization/IImportSerializerService.cs, commercetools.Sdk/commercetools.Sdk.ImportApi/Serialization/SerializerService.cs, commercetools.Sdk/commercetools.Sdk.MLApi/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Sdk.MLApi/Serialization/IMLSerializerService.cs, commercetools.Sdk/commercetools.Sdk.MLApi/Serialization/SerializerService.cs
- add interfaces to serializer services of the different packages. Closes #221
=> add serializer interfaces for different APIs

commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/PollyTest.cs, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/ClientsFactoryTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/TokenProviderTests.cs, commercetools.Sdk/commercetools.Base.Client/Middlewares/AuthorizationMiddleware.cs, commercetools.Sdk/commercetools.Base.Client/Tokens/ITokenProvider.cs, commercetools.Sdk/commercetools.Base.Client/Tokens/TokenProvider.cs
=> refactor token provider to use token promise to avoid long locks

commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/RequestBuilderTests.cs, commercetools.Sdk/commercetools.Base.Client/ApiMethod.cs, commercetools.Sdk/commercetools.Base.Client/commercetools.Base.Client.csproj
remove WebUtitlity dependency - Closes #236
=> remove webutility dependency

commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Instrumentation.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Program.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/README.md, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/Startup.cs, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/appsettings.json, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/commercetools.Api.CheckoutApp.csproj, otel/.env, otel/README.md, otel/docker-compose.yaml, otel/src/grafana/grafana.ini, otel/src/grafana/provisioning/dashboards/general.yaml, otel/src/grafana/provisioning/dashboards/general/Opentelemetry Collector Data Flow.json, otel/src/grafana/provisioning/dashboards/general/demo-dashboard.json, otel/src/grafana/provisioning/dashboards/general/opentelemetry-collector.json, otel/src/grafana/provisioning/dashboards/general/spanmetrics-dashboard.json, otel/src/grafana/provisioning/datasources/default.yaml, otel/src/grafana/provisioning/datasources/jaeger.yaml, otel/src/otelcollector/otelcol-config-extras.yml, otel/src/otelcollector/otelcol-config.yml, otel/src/otelcollector/otelcol-observability.yml, otel/src/prometheus/prometheus-config.yaml
=> OpenTelemetry

.github/workflows/ci.yml, .github/workflows/release.yml, commercetools.Sdk/Examples/commercetools.Api.CheckoutApp/commercetools.Api.CheckoutApp.csproj, commercetools.Sdk/Examples/commercetools.Api.ConsoleApp/commercetools.Api.ConsoleApp.csproj, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/PollyTest.cs, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/commercetools.Api.IntegrationTests.csproj, commercetools.Sdk/IntegrationTests/commercetools.GraphQL.Api.IntegrationTests/commercetools.GraphQL.Api.IntegrationTests.csproj, commercetools.Sdk/IntegrationTests/commercetools.ImportApi.IntegrationTests/commercetools.ImportApi.IntegrationTests.csproj, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/AttributesTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/MessagesTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/commercetools.Api.Serialization.Tests.csproj, commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/commercetools.Sdk.Api.Tests.csproj, commercetools.Sdk/Tests/commercetools.Sdk.HistoryApi.Tests/commercetools.Sdk.HistoryApi.Tests.csproj, commercetools.Sdk/Tests/commercetools.Sdk.ImportApi.Tests/commercetools.Sdk.ImportApi.Tests.csproj, commercetools.Sdk/Tests/commercetools.Sdk.MLApi.Tests/commercetools.Sdk.MLApi.Tests.csproj, commercetools.Sdk/commercetools.Base.Client/commercetools.Base.Client.csproj, commercetools.Sdk/commercetools.Base.Registration/commercetools.Base.Registration.csproj, commercetools.Sdk/commercetools.Base.Serialization/commercetools.Base.Serialization.csproj, commercetools.Sdk/commercetools.Sdk.Api/Predicates/Query/GeoJsonPredicateBuilder.cs, commercetools.Sdk/commercetools.Sdk.Api/commercetools.Sdk.Api.csproj, commercetools.Sdk/commercetools.Sdk.ImportApi/Generated/Client/RequestBuilders/ImportContainers/ByProjectKeyImportContainersByImportContainerKeyImportOperationsGet.cs, commercetools.Sdk/commercetools.Sdk.ImportApi/Generated/Client/RequestBuilders/ImportContainers/ByProjectKeyImportContainersGet.cs, commercetools.Sdk/commercetools.Sdk.MLApi/Generated/Client/RequestBuilders/Recommendations/ByProjectKeyRecommendationsGeneralCategoriesGet.cs, commercetools.Sdk/commercetools.Sdk.MLApi/Generated/Client/RequestBuilders/Recommendations/ByProjectKeyRecommendationsProjectCategoriesByProductIdGet.cs, commercetools.Sdk/compat/commercetools.Sdk.BCTest/commercetools.Sdk.BCTest.csproj, commercetools.Sdk/compat/commercetools.Sdk.V2Compat/commercetools.Sdk.V2Compat.csproj
=> Update dependencies to dotnet 6

commercetools.Sdk/commercetools.Sdk.Api/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/MapperTypeRetrievers/AttributeMapperTypeRetriever.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/MapperTypeRetrievers/AttributeTypeRetriever.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/MapperTypeRetrievers/FieldMapperTypeRetriever.cs
=> change priority for attribute type deserialization

commercetools.Sdk/commercetools.Base.Client/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Base.Client/ILoggerHandlerFactory.cs, commercetools.Sdk/commercetools.Base.Client/LoggerHandlerFactory.cs
=> add option to register custom loggerhandler

commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/InMemoryLogger.cs, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/InMemoryLoggerProvider.cs, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/LoggingTest.cs, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/commercetools.Api.IntegrationTests.csproj
=> add test for custom logging

README.md
Removes references to ML from the readme file.
=> Remove ML from readme

commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/CorrelationIdProviderTest.cs, commercetools.Sdk/commercetools.Base.Client/ClientFactory.cs, commercetools.Sdk/commercetools.Base.Client/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Base.Client/Middlewares/CorrelationIdMiddleware.cs
=> support custom correlation id provider

commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/AttributesTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/Resources/Attributes/MixedSetAttribute.json, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/SerializationFixture.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/ISerializationConfiguration.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/JsonConverters/AttributeConverter.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/MapperTypeRetrievers/AttributeTypeRetriever.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/SerializationConfiguration.cs
=> add option to specify attribute type mapping explicit

commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/Type/TypeIntegrationTests.cs, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/commercetools.Api.IntegrationTests.csproj, commercetools.Sdk/commercetools.Sdk.GraphQL.Api/config.zeroql.json
=> fix resolving of custom fields in GraphQL module

commercetools.Sdk/commercetools.Base.Client/commercetools.Base.Client.csproj, commercetools.Sdk/commercetools.Base.Registration/commercetools.Base.Registration.csproj, commercetools.Sdk/commercetools.Base.Serialization/commercetools.Base.Serialization.csproj, commercetools.Sdk/commercetools.Sdk.Api/commercetools.Sdk.Api.csproj, commercetools.Sdk/commercetools.Sdk.HistoryApi/commercetools.Sdk.HistoryApi.csproj, commercetools.Sdk/commercetools.Sdk.ImportApi/commercetools.Sdk.ImportApi.csproj, commercetools.Sdk/compat/commercetools.Sdk.V2Compat/commercetools.Sdk.V2Compat.csproj
=> Update to .NET 6

commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/ProductSearchDeserializationTest.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/Resources/ProductSearch/facets.json, commercetools.Sdk/commercetools.Sdk.Api/Serialization/JsonConverters/ProductSearchFacetConverter.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/SerializerService.cs
=> add converter for product search facets

commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/ProductTailoringAttributesTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/Resources/ProductTailorings/List.json, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/Resources/ProductTailorings/MixedSetAttribute.json, commercetools.Sdk/commercetools.Sdk.Api/DependencyInjectionSetup.cs, commercetools.Sdk/commercetools.Sdk.Api/Extensions/AttributeExtensions.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/ProductTailorings/IProductTailoringAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/ProductTailorings/ProductTailoringAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/BooleanAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/DecimalAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/LocalizedEnumAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/LocalizedStringAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/LongAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/MoneyAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/PlainEnumAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/ReferenceAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/SetAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Products/StringAttribute.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/JsonConverters/ProductTailoringAttributeConverter.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/MapperTypeRetrievers/ProductTailoringAttributeMapperTypeRetriever.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/MapperTypeRetrievers/ProductTailoringAttributeTypeRetriever.cs, commercetools.Sdk/commercetools.Sdk.Api/Serialization/SerializerService.cs
=> [DEVX-551] add json converter for ProductTailoringAttributes

commercetools.Sdk/commercetools.Sdk.Api/Models/Common/LocalizedString.cs
Thanks @sommmen for the suggestion
Closes #419
=> Add constructors to LocalizedString

commercetools.Sdk/commercetools.Base.Client/commercetools.Base.Client.csproj, commercetools.Sdk/commercetools.Base.Serialization/commercetools.Base.Serialization.csproj, commercetools.Sdk/commercetools.Sdk.Api/commercetools.Sdk.Api.csproj
=> bump system.text.json

commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/MessagesTests.cs, commercetools.Sdk/Tests/commercetools.Api.Serialization.Tests/Resources/Messages/NotificationPayloads.json, commercetools.Sdk/commercetools.Base.Serialization/JsonConverters/DeserializeAsConverterFactory.cs, commercetools.Sdk/commercetools.Base.Serialization/JsonConverters/TypeDiscriminatorConverter.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Subscriptions/IDeliveryPayload.cs
=> Events sdk fixes

commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyBusinessUnitsGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyCartDiscountsGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyCartsGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyCustomersGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyMeCartsGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyMeOrdersGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyOrdersGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyQuoteRequestsGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyQuotesGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/InStore/ByProjectKeyInStoreKeyByStoreKeyStagedQuotesGet.cs
=> add instore query methods

commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/CustomFieldsTest.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/Types/IFieldContainer.cs
=> Fix NPE for AsDecimal extension methods

commercetools.Sdk/Examples/commercetools.Api.ApmExample/appsettings.json, commercetools.Sdk/Examples/commercetools.Api.ConsoleApp/Program.cs, commercetools.Sdk/Examples/commercetools.Api.NewRelicExample/appsettings.json
=> Add region addresses to Example

commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/CustomObject/CustomObjectsIntegrationTests.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/CustomObjects/ByProjectKeyCustomObjectsByContainerByKeyGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/CustomObjects/ByProjectKeyCustomObjectsByContainerGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/CustomObjects/ByProjectKeyCustomObjectsGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/CustomObjects/ByProjectKeyCustomObjectsPost.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/CustomObjects/GenericCustomObject.cs, commercetools.Sdk/commercetools.Sdk.Api/Models/ResourcePagedQueryResponse.cs
=> add generic custom object

commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/Checkout/CheckoutIntegrationTests.cs, commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/CustomObject/CustomObjectsIntegrationTests.cs, commercetools.Sdk/Tests/commercetools.Sdk.CheckoutApi.Tests/Generated/Client/RequestBuilders/PaymentIntents/ByProjectKeyPaymentIntentsByPaymentIdTest.cs, commercetools.Sdk/Tests/commercetools.Sdk.CheckoutApi.Tests/Generated/Client/RequestBuilders/Transactions/ByProjectKeyTransactionsByIdTest.cs, commercetools.Sdk/Tests/commercetools.Sdk.CheckoutApi.Tests/Generated/Client/RequestBuilders/Transactions/ByProjectKeyTransactionsKeyByKeyTest.cs, commercetools.Sdk/Tests/commercetools.Sdk.CheckoutApi.Tests/Generated/Client/RequestBuilders/Transactions/ByProjectKeyTransactionsTest.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/CustomObjects/ByProjectKeyCustomObjectsByContainerByKeyGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/CustomObjects/ByProjectKeyCustomObjectsByContainerGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/CustomObjects/ByProjectKeyCustomObjectsGet.cs, commercetools.Sdk/commercetools.Sdk.Api/Client/RequestBuilders/CustomObjects/ByProjectKeyCustomObjectsPost.cs, commercetools.Sdk/commercetools.Sdk.CheckoutApi/Client/CheckoutApiRoot.cs, commercetools.Sdk/commercetools.Sdk.CheckoutApi/Client/ProjectApiRoot.cs
=> fix checkout SDK
